spring:
  application:
    name: telegrambot
  kafka:
    template:
      default-topic: telegram
    bootstrap-servers: localhost:9092

bot:
  name: HukisingBot
  token: 7875396019:AAEA7ACi0FA-9bkyuBiDd8yrnE6XZcKJKqk
