spring:

  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : products
          uri : lb://PRODUCTS
          predicates:
            - Path=/sneaker/v1/**,/short/v1/**,/tshirt/v1/**
          filters:
            - AddRequestHeader=Method, POST
            - AddRequestHeader=Method, DELETE
        - id: authentication
          uri: lb://AUTHORIZATION
          predicates:
            - Path=/registration/**,/login/**,/authentication/**
          filters:
            - AddRequestHeader=Method, POST

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8090