spring:

  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : products
          uri : lb://PRODUCTS
          predicates:
            - Path=/sneaker/v1/**
        - id: authentication
          uri: lb://AUTHORIZATION
          predicates:
            - Path=/login/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8090