management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  application:
    name: products
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
      profile:
