spring:
  application:
    name: authorization
  config:
    import: optional:configserver:http://localhost:8888


token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
