eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  kafka:
    template:
      default-topic: order
    bootstrap-servers: kafka:9092

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/OnlineStore'
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8020
