spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/OnlineStore'
    username: postgres
    password: admin

  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  kafka:
    template:
      default-topic: product
    bootstrap-servers: localhost:9092

eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8071
