spring:
  application:
    name: Config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8888
